name: deploy to lambda
on:
  push:
    branches:
      - corte3
      - main

jobs:
  deploy_miPrimeraLambdaGitHub:
    name: deploy miPrimeraLambdaGitHub from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: deploy miPrimeraLambdaGitHub
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_1 }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_1 }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: SaludoSimple
          source: saludo_simple.py

  deploy_suma:
    name: deploy suma lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: deploy suma lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: Calculadora
          source: calculadora.py
